AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hc_unicamp_crawler_function

  Sample SAM Template for hc_unicamp_crawler_function

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  HCUnicampCrawlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hospitals/hc_unicamp/hc_unicamp_crawler_function/hc_unicamp_blood_status
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: hospitals_blood_status
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Schedule
          Properties:
            Schedule: cron(0 5 * * ? *)
