AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hc_unicamp_crawler_function

  Sample SAM Template for hc_unicamp_crawler_function

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  HospitalRecordsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/last_hospital_records
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies: 
        - DynamoDBReadPolicy:
            TableName: hospitals_blood_status
      Architectures:
        - x86_64
      Events:
        LastHospitalRecordsApi:
          Type: Api
          Properties:
            Path: /v1/hospitals/records
            Method: get
  HCUnicampCrawlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hospitals/hc_unicamp/hc_unicamp_crawler_function/hc_unicamp_blood_status
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: hospitals_blood_status
      Architectures:
        - x86_64
      Events:
        HCUnicampCrawlerCron:
          Type: Schedule
          Properties:
            Schedule: cron(0 5 * * ? *)

Outputs:
  HospitalsRecordsApi:
    Description: "API Gateway endpoint URL for Prod stage for HospitalRecords function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/v1/hospitals/records/"
  HospitalRecordsFunction:
    Description: "HospitalRecords Lambda Function ARN"
    Value: !GetAtt HospitalRecordsFunction.Arn
  HospitalRecordsFunctionIamRole:
    Description: "Implicit IAM Role created for HospitalRecords function"
    Value: !GetAtt HospitalRecordsFunctionRole.Arn
